### ISSUE TITLE
When installing choreonoid

### ISSUE THREAD

**Issue by yoneken** [fkanehiro/drcutil#2]
I got a following error.

> roboy@roboy:~/src/choreonoid/build$ sudo make install
> .
> .
> .
> CMake Error at ext/hrpcnoid/model/HRP2SH/cmake_install.cmake:36 (FILE):
>   file INSTALL cannot find "/home/roboy/openrtp/lib/PDservo.so".
> Call Stack (most recent call first):
>   ext/hrpcnoid/model/cmake_install.cmake:41 (INCLUDE)
>   ext/hrpcnoid/cmake_install.cmake:37 (INCLUDE)
>   ext/cmake_install.cmake:37 (INCLUDE)
>   cmake_install.cmake:71 (INCLUDE)
> 
> make: **\* [install] Error 1

At https://github.com/jrl-umi3218/hrpcnoid/blob/master/model/HRP2SH/CMakeLists.txt#L11m there is a fixed path to the PDservo.so. However, there is not that one in my environment.

**Comment by fkanehiro** [comment]
Since PDservo.so contains confidential information, it is not on Github. I'll send it to you later by E-mail.

@s-nakaoka
I don't like to copy existing files. Do you really need to copy?

**Comment by yoneken** [comment]
Thank you for Kanehiro-san.

I resumed to install with sended binaries, then I got another error.
I move the issue to the hrpcnoid project. https://github.com/jrl-umi3218/hrpcnoid/issues/1
